/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Conexao;
import dao.ContaDB;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import model.entities.Conta;

/**
 *
 * @author User
 */
public class TelaSaque extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */    

    public TelaSaque() {
        initComponents();
        txtValor.setEnabled(false);
        btnSacar.setEnabled(false);
    }

    public String mensagemSenha() {
        JLabel labelMensagem = new JLabel("Digite a senha: ");
        JPasswordField txtSenha = new JPasswordField();
        JOptionPane.showConfirmDialog(null, new Object[]{labelMensagem, txtSenha}, "Senha: ", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        txtSenha.requestFocus();
        String senha = new String(txtSenha.getPassword());
        return senha;
    }
    
    /*esse método foi criado para guardar os dados da conta buscados na TelaInicial.java
      por que? A TelaInicial.java possúi 2 labels com o código e dv das contas, com isso
      é buscado no banco e passado para essa classe.
      Foi tentado passar a conta que a TelaInicial recebe no construtor, mas não foi possível.
    */
    Conta conta = new Conta();
    public void guardarConta(Conta conta) {
        this.conta.setCodigo(conta.getCodigo());
        this.conta.setDigitoVerificador(conta.getDigitoVerificador());
        this.conta.setTipoConta(conta.getTipoConta());
        this.conta.setAgencia(conta.getAgencia());
        this.conta.setCliente(conta.getCliente());
        this.conta.setSaldo(conta.getSaldo());
    }

    //VARIAVEIS    
    Double valorSaque = null;

    private void realizarSaque(Double valorSaque) {
        Conexao conexao = new Conexao();
        ContaDB contaDB = new ContaDB(conexao);
        Double saldoConta = contaDB.getSaldoConta(conta.getCodigo(), conta.getDigitoVerificador());
        if (saldoConta > valorSaque) {
            String senha = mensagemSenha();
            Boolean senhaValida = contaDB.validarSenha(senha, conta.getCodigo());

            if (senhaValida) {
                Boolean sucessoSaque = contaDB.sacar(valorSaque, conta.getCodigo());
                if (sucessoSaque) {
                    JOptionPane.showMessageDialog(null, "Saque realizado com sucesso.", "Saque", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao realizar saque.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Senha inválida.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Saldo insuficiente.", "Atenção", JOptionPane.WARNING_MESSAGE);
            TelaInicial tela = new TelaInicial(conta);
            this.dispose();
            tela.setVisible(true);
        }
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnCem = new javax.swing.JButton();
        btnDuzentos = new javax.swing.JButton();
        btnTrezentos = new javax.swing.JButton();
        btnCentoECinquenta = new javax.swing.JButton();
        btnDuzentosECinquenta = new javax.swing.JButton();
        btnOutroValor = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        btnSacar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sacar");
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo.setText("Selecione o valor:");

        btnCem.setText("100");
        btnCem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCemActionPerformed(evt);
            }
        });

        btnDuzentos.setText("200");
        btnDuzentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuzentosActionPerformed(evt);
            }
        });

        btnTrezentos.setText("300");
        btnTrezentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrezentosActionPerformed(evt);
            }
        });

        btnCentoECinquenta.setText("150");
        btnCentoECinquenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentoECinquentaActionPerformed(evt);
            }
        });

        btnDuzentosECinquenta.setText("250");
        btnDuzentosECinquenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuzentosECinquentaActionPerformed(evt);
            }
        });

        btnOutroValor.setText("Outro");
        btnOutroValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutroValorActionPerformed(evt);
            }
        });

        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFocusLost(evt);
            }
        });

        btnSacar.setText("Sacar");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDuzentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrezentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDuzentosECinquenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCentoECinquenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOutroValor, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCentoECinquenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDuzentos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDuzentosECinquenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOutroValor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrezentos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSacar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDuzentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuzentosActionPerformed
        // TODO add your handling code here:
        valorSaque = 200.00;
        realizarSaque(valorSaque);
    }//GEN-LAST:event_btnDuzentosActionPerformed

    private void btnOutroValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutroValorActionPerformed
        // TODO add your handling code here:
        if (!txtValor.isEnabled()) {
            txtValor.setEnabled(true);
            btnSacar.setEnabled(true);
            txtValor.requestFocus();            
            btnCem.setEnabled(false);
            btnCentoECinquenta.setEnabled(false);
            btnDuzentos.setEnabled(false);
            btnDuzentosECinquenta.setEnabled(false);
            btnTrezentos.setEnabled(false);
        }                
    }//GEN-LAST:event_btnOutroValorActionPerformed

    private void btnCemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCemActionPerformed
        // TODO add your handling code here:        
        valorSaque = 100.00;
        realizarSaque(valorSaque);

    }//GEN-LAST:event_btnCemActionPerformed

    private void btnTrezentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrezentosActionPerformed
        // TODO add your handling code here:
        valorSaque = 300.00;
        realizarSaque(valorSaque);
    }//GEN-LAST:event_btnTrezentosActionPerformed

    private void btnCentoECinquentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentoECinquentaActionPerformed
        // TODO add your handling code here:
        valorSaque = 150.00;
        realizarSaque(valorSaque);
    }//GEN-LAST:event_btnCentoECinquentaActionPerformed

    private void btnDuzentosECinquentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuzentosECinquentaActionPerformed
        // TODO add your handling code here:
        valorSaque = 250.00;
        realizarSaque(valorSaque);
    }//GEN-LAST:event_btnDuzentosECinquentaActionPerformed

    private void txtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusLost

    }//GEN-LAST:event_txtValorFocusLost

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        // TODO add your handling code here:
        if (!txtValor.getText().isEmpty() && Double.parseDouble(txtValor.getText()) != 0) {
            valorSaque = Double.parseDouble(txtValor.getText());
            realizarSaque(valorSaque);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor informe o valor do saque.", "Atenção", JOptionPane.WARNING_MESSAGE);
            txtValor.setEnabled(true);
            txtValor.requestFocus();            
        }
    }//GEN-LAST:event_btnSacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInformarContaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInformarContaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInformarContaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInformarContaDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSaque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCem;
    private javax.swing.JButton btnCentoECinquenta;
    private javax.swing.JButton btnDuzentos;
    private javax.swing.JButton btnDuzentosECinquenta;
    private javax.swing.JButton btnOutroValor;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnTrezentos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
